const CATEGORIES = [
  { id: 1, name: "Tibbiyot va farmasevtika", icon: "fa-heartbeat", color: "#e74c3c", count: 3 },
  { id: 2, name: "Iqtisod va boshqaruv", icon: "fa-chart-line", color: "#16a085", count: 6 },
  { id: 3, name: "Falsafa", icon: "fa-lightbulb", color: "#8e44ad", count: 4 },
  { id: 4, name: "Filologiya", icon: "fa-language", color: "#2980b9", count: 6 },
  { id: 5, name: "Texnika va texnologiyalar", icon: "fa-cogs", color: "#7f8c8d", count: 9 },
  { id: 6, name: "Biologiya", icon: "fa-dna", color: "#27ae60", count: 4 },
  { id: 7, name: "Harbiy ta'lim", icon: "fa-shield-alt", color: "#2c3e50", count: 7 },
  { id: 8, name: "Pedagogika", icon: "fa-chalkboard-teacher", color: "#c0392b", count: 5 },
  { id: 9, name: "Fizika", icon: "fa-atom", color: "#1abc9c", count: 3 },
  { id: 10, name: "Yuridik fanlar", icon: "fa-balance-scale", color: "#34495e", count: 3 },
  { id: 11, name: "Matematika", icon: "fa-square-root-alt", color: "#d35400", count: 2 },
  { id: 12, name: "Qishloq xo'jaligi", icon: "fa-seedling", color: "#9b59b6", count: 2 },
];

const AUTHORS = [
  { id: 1, fullname: "Ахророва Шахноза Отабек қизи", country: "O'zbekiston" },
  { id: 2, fullname: "Sabirova Gulnoza Xidirbayevna", country: "O'zbekiston" },
  { id: 3, fullname: "Ummatov Bekzod Xamzayevich", country: "O'zbekiston" },
  { id: 4, fullname: "Maxkamov Ulug‘bek Abdugapporovich", country: "O'zbekiston" },
  { id: 5, fullname: "Xashimova Xurshida Djuraxanovna", country: "O'zbekiston" },
  { id: 6, fullname: "Usmonov Saidikromxoʻja Saidaliyevich", country: "O'zbekiston" },
  { id: 7, fullname: "Sultonov Oybek Komiljonovich", country: "O'zbekiston" },
  { id: 8, fullname: "Kamolova Zaynura Mehriddin qizi", country: "O'zbekiston" },
  { id: 9, fullname: "Abdurasulov Shuxrat Ergashevich", country: "O'zbekiston" },
  { id: 10, fullname: "Ismoilova Dildora Erkinovna", country: "O'zbekiston" },
  { id: 11, fullname: "Sharipov Doston Hasan o'g'li", country: "O'zbekiston" },
  { id: 12, fullname: "Axmedova Nilufar Shuxratovna", country: "O'zbekiston" },
  { id: 13, fullname: "Xasanov Shaxboz Xasanovich", country: "O'zbekiston" },
  { id: 14, fullname: "Dexqonov Avazbek Tolibjon O'g'li", country: "O'zbekiston" },
  { id: 15, fullname: "Bobokulova Nilufar Xayrullo kizi", country: "O'zbekiston" },
  { id: 16, fullname: "Abduqahhorova Xosiyat Abdurasul qizi", country: "O'zbekiston" },
  { id: 17, fullname: "Yusupjanova Shaxnoz Mirzatillayevna", country: "O'zbekiston" },
  { id: 18, fullname: "Badalboyev Feruz Yusufovich", country: "O'zbekiston" },
  { id: 19, fullname: "Sattarov Abdisamat Umirqulovich", country: "O'zbekiston" },
  { id: 20, fullname: "O'rinboyev Islomjon Yunusali o'g'li", country: "O'zbekiston" },
  { id: 21, fullname: "Xolmatov Qodirjon Maxmudovich", country: "O'zbekiston" },
  { id: 22, fullname: "Toshmatov Baxtiyor Raximovich", country: "O'zbekiston" },
  { id: 23, fullname: "William Shakespeare", country: "Angliya" },
  { id: 24, fullname: "Gabriel Garcia Marquez", country: "Kolumbiya" },
  { id: 25, fullname: "Fyodor Dostoevskiy", country: "Rossiya" },
  { id: 26, fullname: "Ernest Hemingway", country: "AQSh" },
  { id: 27, fullname: "Albert Einstein", country: "Germaniya" },
  { id: 28, fullname: "Marie Curie", country: "Fransiya" },
  { id: 29, fullname: "Stephen Hawking", country: "Angliya" },
  { id: 30, fullname: "Sharipov D.H", country: "O'zbekiston" },
  { id: 31, fullname: "Norqulov Bahodir Musulmanovich", country: "O'zbekiston" },
  { id: 32, fullname: "Titova Natalya Olegovna", country: "O'zbekiston" },
  { id: 33, fullname: "Zulponov Shovqiddin O'rozalievich", country: "O'zbekiston" },
  { id: 34, fullname: "Saidnazarova Gulshan Bolta qizi", country: "O'zbekiston" },
];

const BOOKS = [
  { id: 1, title: "COVID-19 bilan og'rigan keksa bemorlarda surunkali yurak yetishmovchiligini davolash", description: "Keksа yoshli bemorlarda COVID-19 o'tkazgan va o'tkazmagan hollarda klinik, instrumentallar va biokimyoviy ko'rsatkichlarni baholash, ularning o'zaro bog'liqligini aniqlash hamda yuqori xavf guruhlarini ajratib, individual profilaktika-reabilitatsiya choralarni ishlab chiqish.",
    image: "images/covers/01.png", author_id: 1, category_id: 1, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10012851/NsTEK1mShb5C9dA.pdf", book_url: "https://library.ziyonet.uz/book/148031",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 2, title: "Oftalmologik kasalliklarni erta tashxislashda sun'iy intellekt texnologiyalari", description: "Oftalmologik kasalliklarni erta aniqlash, klinik kuzatuv va davolashni rejalashtirishda raqamli texnologiyalar, sun'iy intellekt hamda teleoftalmologiya yondashuvlarining klinik-amaliy ahamiyati tizimli tahlil qilingan.",
    image: "images/covers/02.png", author_id: 2, category_id: 1, genre: "Monografiya", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 113, pdf_url: "https://api.ziyonet.uz/uploads/books/10003819/9VGkMQBoWSNNaNJ.pdf", book_url: "https://library.ziyonet.uz/book/148021",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 3, title: "Yuqori likvidli va monopol mahsulotlar bozorini tartibga solish", description: "Yuqori likvidli va monopol mahsulotlar bozorini tartibga solishning moliyaviy-kredit mexanizmini takomillashtirishga qaratilgan taklif va tavsiyalar ishlab chiqish.",
    image: "images/covers/03.png", author_id: 3, category_id: 2, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10012851/0LVAKGYm0qf25By.pdf", book_url: "https://library.ziyonet.uz/book/148034",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 4, title: "Dialogning ilmiy ijodiy faoliyatga ta'siri", description: "Dialogning transformativ, kognitiv, germenevtik mexanizmlarining ilmiy-ijodiy faoliyatda yangilik yaratish, ma'no shakllantirish va bilimlar rekonstruksiyasini modellashtirishning universal metodologik omili sifatidagi falsafiy-metodologik jihatlari.",
    image: "images/covers/04.png", author_id: 4, category_id: 3, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10012851/LrJZXNM15FDSySA.pdf", book_url: "https://library.ziyonet.uz/book/148033",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 5, title: "Xorazm shoirlari asarlari tilida intertekstuallik", description: "Intertekstuallik hodisasining Xorazm she'riy matnlardagi rolini belgilash, Xorazm she'riy matnlarining mazmuniy idrokida intertekstuallikni yuzaga keltiruvchi til birliklarining o'rnini ochib berish.",
    image: "images/covers/05.png", author_id: 5, category_id: 4, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10012851/0zJTjFx080wsSth.pdf", book_url: "https://library.ziyonet.uz/book/148030",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 6, title: "Ingliz va o'zbek tillarida fonologik sath birliklari", description: "Hozirgi zamon ingliz va o'zbek tillarida lisoniy belgi gradatsiyasining fonologik/fonetik sath birliklari paradigmalarini shakllantirishi jihatlarini ochib berish.",
    image: "images/covers/06.png", author_id: 6, category_id: 4, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10012851/5mf0JLMvao1N1PA.pdf", book_url: "https://library.ziyonet.uz/book/148029",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 7, title: "Tirik ipak qurti g'umbagini jonsizlantirish va quritish qurilmasi", description: "Tirik ipak qurti g'umbagini jonsizlantirish va quritish uchun kombinatsiyalashgan qurilmani takomillashtirishdan iborat.",
    image: "images/covers/07.png", author_id: 7, category_id: 5, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10012851/iUk62xAMntx5pgU.pdf", book_url: "https://library.ziyonet.uz/book/148027",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 8, title: "Ikki fazali erituvchi muhitida kalsiy va rux stearatlarni olish", description: "Ikki fazali erituvchi muhitida kalsiy va rux stearatlarni olishning iqtisodiy samarador texnologiyasini ishlab chiqish va qo'llash.",
    image: "images/covers/08.png", author_id: 8, category_id: 5, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10012852/3AmIdUvkb9Tm0kK.pdf", book_url: "https://library.ziyonet.uz/book/148025",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 9, title: "Beton qorishmalari uchun polikarboksilat superplastifikator", description: "Polikarboksilat superplastifikatorini sintez qilish, olish texnologiyasini ishlab chiqish va sement-qorishmalarida qo'llash.",
    image: "images/covers/09.png", author_id: 9, category_id: 5, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10012852/wmYjKTeZNb6BIxp.pdf", book_url: "https://library.ziyonet.uz/book/148024",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 10, title: "Suv chiqarish inshootlari byeflari tutashishida oqim energiyasi", description: "Suv chiqarish inshootlari byeflari tutashishida oqim energiyasini so'ndirishni ilmiy va eksperimental asoslash.",
    image: "images/covers/10.png", author_id: 10, category_id: 5, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10012852/nLKEebhEwraMNLe.pdf", book_url: "https://library.ziyonet.uz/book/148023",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 11, title: "Beton bilan qoplangan o'zanlarning gidravlik qarshiligi", description: "O'zani beton bilan qoplangan kanallarning gidravlik qarshiligi va o'tkazuvchanlik qobiliyatini baholash.",
    image: "images/covers/11.png", author_id: 11, category_id: 5, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "Rus", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10012852/UfhjaTurOLexbiB.pdf", book_url: "https://library.ziyonet.uz/book/148022",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 12, title: "Polifenilensulfidlar asosida ugleplastlar olish texnologiyasi", description: "Polifenilensulfid bilan PAN tolasi asosida yuqori haroratga barqaror va fizik mexanik xossalari yuqori ugleplast olish texnologiyasini ishlab chiqish.",
    image: "images/covers/12.png", author_id: 12, category_id: 5, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/REYckd3SHmYcrdP.pdf", book_url: "https://library.ziyonet.uz/book/148013",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 13, title: "Suyuq shishadan olovbardosh kompozitsiyalar olish", description: "Suyuq shishani modifikatsiyalab olovbardosh kompozitsiyalarning olinishi, xossalari va texnologiyasini ishlab chiqish.",
    image: "images/covers/13.png", author_id: 13, category_id: 5, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/BB2JJkJ2VUNaAe6.pdf", book_url: "https://library.ziyonet.uz/book/148009",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 14, title: "Toshkent viloyati baliqchilik xo'jaliklarida ekologik omillar", description: "Karpsimon baliqlarni yetishtirishda ekologik omillar va texnologiyalarning ularning hayotiy jarayonlariga ta'sirini baholash hamda baliq mahsulotlari xavfsizligini ta'minlash.",
    image: "images/covers/14.png", author_id: 14, category_id: 6, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/2EKpLzwURAkFzQw.pdf", book_url: "https://library.ziyonet.uz/book/148017",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 15, title: "G. Hirsutum L. genotipida xo'jalik belgilari populyatsiyasi", description: "G'o'zaning G. hirsutum L. turichi chatishtirishlardan olingan tizmasida muhim xo'jalik belgilarining paydo bo'lishida genotip x muhit ta'sirini aniqlash.",
    image: "images/covers/15.png", author_id: 15, category_id: 6, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/SDRHCcPPPRgAz5t.pdf", book_url: "https://library.ziyonet.uz/book/148016",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 16, title: "Shimoliy-sharqiy O'zbekistonning Puccinia turlari", description: "Shimoliy-sharqiy O'zbekistonda tarqalgan yuksak o'simliklarda uchraydigan Puccinia turlarini aniqlash, taksonomik tahlil qilish, bioekologiyasi va filogeniyasi.",
    image: "images/covers/16.png", author_id: 16, category_id: 6, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/BrERKlJejIZFcAh.pdf", book_url: "https://library.ziyonet.uz/book/148015",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 17, title: "Imom Ismoil al-Buxoriyning ma'naviy-axloqiy qarashlari", description: "Imom Ismoil al-Buxoriyning ma'naviy-axloqiy qarashlarini o'rganish, ularning tarbiyaviy va pedagogik ahamiyatini ochib berish.",
    image: "images/covers/17.png", author_id: 17, category_id: 3, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10009804/n0QTrZKyu1WfwZc.pdf", book_url: "https://library.ziyonet.uz/book/148012",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 18, title: "Kiberzo'rvonlikka qarshi kiberxavfsizlik mafkurasi", description: "Kiberzo'rvonlik va kiberxavfsizlik g'oyalarining shakllanishi, rivojlanish qonuniyatlari, kiber makonda shaxs va jamiyat xavfsizligini ta'minlashning mafkuraviy asoslari.",
    image: "images/covers/18.png", author_id: 18, category_id: 3, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/Ajh7xfwtoIbkVfv.pdf", book_url: "https://library.ziyonet.uz/book/148019",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 19, title: "O'zbekistonda oila institutidagi ijtimoiy o'zgarishlar", description: "Globallashuv sharoitida oila instituti xarakteridagi o'zgarishlarning ijtimoiy-falsafiy xususiyatlarini ochib berish.",
    image: "images/covers/19.png", author_id: 19, category_id: 3, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/syGRzwKjCuPF096.pdf", book_url: "https://library.ziyonet.uz/book/148008",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 20, title: "O'zbek texnik terminlarini standartlashtirish", description: "O'zbek texnik terminologiyasini ilmiy asosda standartlashtirish, terminlarni yagona mezonlar tizimi asosida tartibga solish bo'yicha tavsiyalar.",
    image: "images/covers/20.png", author_id: 20, category_id: 4, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/3lwmTkj2DpFnFix.pdf", book_url: "https://library.ziyonet.uz/book/148018",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 21, title: "Namangan viloyati ziyoratgohlari va muqaddas qadamjolari tarixi", description: "Namangan viloyati ziyoratgohlari va muqaddas qadamjolari tarixi, ular bilan bog'liq urf-odat hamda marosimlarning etnohududiy xususiyatlari.",
    image: "images/covers/21.png", author_id: 21, category_id: 4, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005546/VgCK8VcAoxjYlrD.pdf", book_url: "https://library.ziyonet.uz/book/147994",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 22, title: "O'zbek tilining izohli lug'atida tarixga oid terminlar", description: "Tarixga oid terminlarning O'zbek tilining izohli lug'atida berilishini izohlash, ularning etimologik va semantik tavsifini takomillashtirish.",
    image: "images/covers/22.png", author_id: 22, category_id: 4, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005546/VvnF6YUcTiGrTdr.pdf", book_url: "https://library.ziyonet.uz/book/147993",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 23, title: "Semantic analysis of proverbs with somatic component", description: "Ingliz va o'zbek tillaridagi bosh komponentli maqollarning semantik tahlili.跨 til kommunikatsiyasi va lingvistik tahlil uchun qimmatli manba.",
    image: "images/covers/23.png", author_id: 11, category_id: 10, genre: "Maqola", year: 2023, publisher: "ZiyoNET", language: "Ingliz", isbn: null, pages: 3, pdf_url: "https://api.ziyonet.uz/uploads/books/10013258/nIRANU7PaaKzhP3.pdf", book_url: "https://library.ziyonet.uz/book/148005",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 24, title: "Tezlatgich majmualarida radioaktivlik va doza yuklamalari", description: "Tezlatgich qurilmalari ish rejimlarida yuzaga keladigan radioaktivlik va doza yuklamalarini tahlil qilish asosida xodimlarning radiatsion xavfsizligini baholash.",
    image: "images/covers/24.png", author_id: 13, category_id: 9, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 58, pdf_url: "https://api.ziyonet.uz/uploads/books/1343700/fI0lPjGh0YXpZCt.pdf", book_url: "https://library.ziyonet.uz/book/148007",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 25, title: "Silikat shishada metall oksidlari diffuziyasi", description: "Legirlangan qo'rg'oshin silikat shishalarda ruteniy atomlari diffuziyasining elektr o'tkazuvchanlik hamda termoEYuK koeffitsientiga ta'siri.",
    image: "images/covers/25.png", author_id: 14, category_id: 9, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/1343700/XpIA09G5aHsUB9B.pdf", book_url: "https://library.ziyonet.uz/book/148006",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 26, title: "Tijorat banklari nodepozit moliyaviy resurslarini optimallashtirish", description: "Tijorat banklari nodepozit moliyaviy resurslarini optimallashtirishning nazariy-uslubiy asoslari hamda kreditlash faoliyatini takomillashtirish.",
    image: "images/covers/26.png", author_id: 7, category_id: 2, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/ZoFxBbkLHvt1HqL.pdf", book_url: "https://library.ziyonet.uz/book/148011",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 27, title: "Korxonalarda riskka asoslangan ichki auditi takomillashtirish", description: "Korxonalarda riskka asoslangan ichki auditi o'tkazishni takomillashtirish bo'yicha ilmiy taklif va amaliy tavsiyalar.",
    image: "images/covers/27.png", author_id: 15, category_id: 2, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "Rus", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/84daItbciHocqzI.pdf", book_url: "https://library.ziyonet.uz/book/148010",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 28, title: "Qurilishda kichik va yirik biznes integratsiyasi", description: "Qurilish sohasida kichik va yirik biznes subyektlari integratsiyasi samaradorligini oshirishning nazariy-uslubiy asoslari.",
    image: "images/covers/28.png", author_id: 12, category_id: 2, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10012852/oqh22EBIIHXxonA.pdf", book_url: "https://library.ziyonet.uz/book/148020",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 29, title: "Mintaqa iqtisodiyotini barqaror rivojlantirish", description: "Mintaqa iqtisodiyotini barqaror rivojlantirishda resurs salohiyatidan foydalanish metodologiyasini takomillashtirish (Surxondaryo misolida).",
    image: "images/covers/29.png", author_id: 16, category_id: 2, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005546/SSoze25lig9XJZL.pdf", book_url: "https://library.ziyonet.uz/book/147987",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 30, title: "Fermionli Fok fazodagi operatorli matritsa spektr tahlili", description: "Panjaradagi soni saqlanmaydigan zarrachalar (fermionlar) sistemasiga mos uchinchi tartibli operatorli matritsa muhim spektrining tuzilishini aniqlash.",
    image: "images/covers/30.png", author_id: 17, category_id: 11, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/baz8sKT0vAjeowc.pdf", book_url: "https://library.ziyonet.uz/book/148014",
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 31, title: "Gospital ta'limda matematika fanini o'qitishning samarali usullari", description: "Gospital ta'limda matematika fanini o'qitishning samarali metodlari va o'quvchilarning mantiqiy fikrlash qobiliyatlarini shakllantirish.",
    image: "images/covers/31.png", author_id: 17, category_id: 8, genre: "Maqola", year: 2025, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 3, pdf_url: "https://api.ziyonet.uz/uploads/books/10010475/mcIYs8f25WrMWrZ.pdf", book_url: "https://library.ziyonet.uz/book/147992",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 32, title: "Maktab yoshidagi bolalarni ta'lim jarayonida fanlarga qiziqtirish", description: "Onkologik va gematologik kasalliklar bilan davolanayotgan o'quvchilarning ta'lim jarayonidagi muammolari va zamonaviy pedagogik yondashuvlar.",
    image: "images/covers/32.png", author_id: 17, category_id: 8, genre: "Maqola", year: 2025, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 5, pdf_url: "https://api.ziyonet.uz/uploads/books/10010475/dY1iOrsEeFAU69B.pdf", book_url: "https://library.ziyonet.uz/book/147991",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 33, title: "Gospital maktab o'quvchilariga milliy qadriyatlar singdirish", description: "Gospital maktab o'quvchilarining milliy-axloqiy qadriyatlar asosida tarbiyalanishi va axloqiy fazilatlarning shakllanishi.",
    image: "images/covers/33.png", author_id: 17, category_id: 8, genre: "Maqola", year: 2025, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 4, pdf_url: "https://api.ziyonet.uz/uploads/books/10010475/7AC11i72gmi3vg5.pdf", book_url: "https://library.ziyonet.uz/book/147990",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 34, title: "O'zbekistonda gospital pedagogika 'Mehrli maktab' faoliyatida", description: "Gospital pedagogika sohasiga oid manba va adabiyotlarni tahlil qilish natijasida Mehrli maktabning faoliyati haqida amaliy harakatlar.",
    image: "images/covers/34.png", author_id: 17, category_id: 8, genre: "Maqola", year: 2024, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 6, pdf_url: "https://api.ziyonet.uz/uploads/books/10010475/b9hkEe3Lmm7sUOG.pdf", book_url: "https://library.ziyonet.uz/book/147989",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 35, title: "Kiberjinoyatlarga oid ishni sudga qadar yuritish", description: "Kiberjinoyatlarga oid ishlar bo'yicha sudga qadar ish yurituv jarayonida raqamli dalillardan foydalanishning tashkiliy-huquqiy mexanizmlari.",
    image: "images/covers/35.png", author_id: 18, category_id: 10, genre: "Avtoreferat", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://api.ziyonet.uz/uploads/books/10005546/AJcnxDcZ85lnBsF.pdf", book_url: "https://library.ziyonet.uz/book/147988",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 36, title: "Harbiy haydovchilarni ekstremal vaziyatlarga tayyorlash", description: "Harbiy haydovchilarni ekstremal vaziyatlarga tayyorlovchi imitatsion trenajyorini ishlab chiqish va qo'llash.",
    image: "images/covers/36.png", author_id: 11, category_id: 7, genre: "Maqola", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 5, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/nuGU4y3f07f17Tv.pdf", book_url: "https://library.ziyonet.uz/book/148003",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 37, title: "Ekstremal holatlarda avtomashinalarni boshqarish moduli", description: "Jamoat xavfsizligini ta'minlashda harbiy haydovchilarni ekstremal holatlarda avtomashinalarni boshqarish moduli asosida kasbiy tayyorgarlik.",
    image: "images/covers/37.png", author_id: 11, category_id: 7, genre: "Maqola", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 5, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/bmVmKFkbjgfuqb5.pdf", book_url: "https://library.ziyonet.uz/book/148002",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 38, title: "Kayzen jarayoni asosida ekstremal vaziyatlarda tayyorlash", description: "Yo'l-transport hodisalarini kamaytirishda kayzen jarayoni asosida ekstremal vaziyatlarda harbiy haydovchilarni kasbiy tayyorlashning yo'nalishlari.",
    image: "images/covers/38.png", author_id: 11, category_id: 7, genre: "Maqola", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 5, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/sZZ3jO7AFCMY6uZ.pdf", book_url: "https://library.ziyonet.uz/book/148001",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 39, title: "Qurolli kuchlarda zirxli texnikalarni modernizasiyalash", description: "Hozirgi kunda SSSR davrida ishlab chiqarilgan harbiy texnikalarda texnik xizmatlar va ta'mir o'tkazish hamda modernizasiyalash samaradorligi.",
    image: "images/covers/39.png", author_id: 30, category_id: 7, genre: "Maqola", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 5, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/oSwKg4De6gOKXRn.pdf", book_url: "https://library.ziyonet.uz/book/147998",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 40, title: "Harbiy haydovchilarning innovatsion mexanizmlari", description: "AQSh, Germaniya, Koreya va Isroil tajribalari asosida harbiy haydovchilarning ekstremal vaziyatlarda kasbiy tayyorgarligini oshirishning innovatsion mexanizmlari.",
    image: "images/covers/40.png", author_id: 11, category_id: 7, genre: "Maqola", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 5, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/C4PrS0W5FlOcKIW.pdf", book_url: "https://library.ziyonet.uz/book/147996",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 41, title: "Harbiy haydovchilarning maxsus mashqlari", description: "Harbiy haydovchilarni xizmat faoliyatlari davomida yo'l-transport hodisalarini kamaytirishga yo'naltirilgan maxsus mashqlar.",
    image: "images/covers/41.png", author_id: 11, category_id: 7, genre: "Maqola", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 5, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/teTn2VhWqalZXY7.pdf", book_url: "https://library.ziyonet.uz/book/147995",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 42, title: "Harbiy haydovchilarni kasbiy tayyorgarligining tarixiy asoslari", description: "O'zbekiston hududida harbiy haydovchilar kasbiy tayyorgarligining tarixiy asoslari - qadimgi saklar, skiflar davridan to hozirgi kunga qadar.",
    image: "images/covers/42.png", author_id: 30, category_id: 7, genre: "Maqola", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 5, pdf_url: "https://api.ziyonet.uz/uploads/books/10005547/tAxPMDebZS9e0X4.pdf", book_url: "https://library.ziyonet.uz/book/147997",
    created_by: "admin", status: "approved", created_at: "2026-07-18" },
  { id: 43, title: "Telemeditsina tizimlarining samaradorligini baholash", description: "Masofaviy tibbiy xizmatlarni joriy etish orqali aholiga tibbiy yordam ko'rsatish sifatini oshirish va tibbiyot xodimlarining malakasini rivojlantirish usullari.",
    image: "images/covers/43.png", author_id: 1, category_id: 1, genre: "Monografiya", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 64, pdf_url: "https://placehold.co/400x600/e74c3c/ffffff?text=PDF", book_url: null,
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 44, title: "Raqamli iqtisodiyot sharoitida biznes modellarini transformatsiya qilish", description: "Zamonaviy raqamli texnologiyalar asosida biznes jarayonlarini qayta tashkil etish va innovatsion yechimlar ishlab chiqish strategiyalari.",
    image: "images/covers/44.png", author_id: 5, category_id: 2, genre: "Monografiya", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 48, pdf_url: "https://placehold.co/400x600/16a085/ffffff?text=PDF", book_url: null,
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 45, title: "Zamonaviy o'zbek nasrida ijtimoiy realizm tamoyillari", description: "O'zbekiston mustaqilligidan keyingi adabiyotda ijtimoiy realizm an'analarining rivojlanishi va zamonaviy nasriy asarlarda ijtimoiy voqelikni aks ettirish usullari.",
    image: "images/covers/45.png", author_id: 7, category_id: 4, genre: "Ilmiy maqola", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 12, pdf_url: "https://placehold.co/400x600/2980b9/ffffff?text=PDF", book_url: null,
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 46, title: "Qayta tiklanadigan energiya manbalarini integratsiya qilish texnologiyalari", description: "Quyosh va shamol energiyasini elektr tarmoqiga ulashda zamonaviy inverter tizimlari va energiya saqlash qurilmalarining samaradorligini oshirish yo'llari.",
    image: "images/covers/46.png", author_id: 9, category_id: 5, genre: "Monografiya", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 56, pdf_url: "https://placehold.co/400x600/7f8c8d/ffffff?text=PDF", book_url: null,
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 47, title: "Genetik muhandislikning zamonaviy yutuqlari va ularning qo'llanilishi", description: "CRISPR-Cas9 texnologiyasi asosida o'simliklar genomini tahrirlash va yangi qishloq xo'jaligi ekinlarini yaratishning nazariy va amaliy asoslari.",
    image: "images/covers/47.png", author_id: 15, category_id: 6, genre: "Monografiya", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 70, pdf_url: "https://placehold.co/400x600/27ae60/ffffff?text=PDF", book_url: null,
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 48, title: "Kiberxavfsizlik sohasida sun'iy intellekt yechimlari", description: "Tarmoq xavfsizligini ta'minlashda mashinali o'qitish algoritmlarining qo'llanilishi, kiber hujumlarni aniqlash va oldini olishning zamonaviy usullari.",
    image: "images/covers/48.png", author_id: 8, category_id: 5, genre: "Monografiya", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 60, pdf_url: "https://placehold.co/400x600/2c3e50/ffffff?text=PDF", book_url: null,
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 49, title: "Masofaviy ta'lim texnologiyalarining samaradorligini oshirish", description: "Onlayn ta'lim platformalarida interaktiv usullarni joriy etish, talabalarning motivatsiyasini oshirish va ta'lim sifatini baholashning zamonaviy yechimlari.",
    image: "images/covers/49.png", author_id: 16, category_id: 8, genre: "Monografiya", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 44, pdf_url: "https://placehold.co/400x600/c0392b/ffffff?text=PDF", book_url: null,
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
  { id: 50, title: "Kvant hisoblash texnologiyalarining nazariy asoslari", description: "Kvant kompyuterlarining arxitekturasi, kvant algoritmlari va ularning kriptografiya, modellashtirish va sun'iy intellekt sohasidagi qo'llanilish imkoniyatlari.",
    image: "images/covers/50.png", author_id: 12, category_id: 9, genre: "Monografiya", year: 2026, publisher: "ZiyoNET", language: "O'zbek", isbn: null, pages: 52, pdf_url: "https://placehold.co/400x600/1abc9c/ffffff?text=PDF", book_url: null,
    created_by: "admin", status: "approved", created_at: "2026-07-20" },
];

const USERS = [
  { id: 1, fullname: "Afruza", username: "afruza", email: "afruza@gmail.com", password: "admin123", role: "admin", avatar: null },
  { id: 2, fullname: "Aziz Karimov", username: "aziz", email: "aziz@gmail.com", password: "123456", role: "user", avatar: null },
  { id: 3, fullname: "Sardor Rakhimov", username: "sardor", email: "sardor@gmail.com", password: "123456", role: "user", avatar: null }
];

const REVIEWS = [];
const RATINGS = [];
